<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();

        DB::table('cards')->insert([
            // =============================================
            // KARTU RISIKO (RISK CARDS)
            // Sumber: 
            // =============================================
            [
                'id' => 'CARD_RISK_01',
                'type' => 'RISK',
                'title' => 'HP Rusak',
                'narration' => 'HP mu rusak! Karena tidak ada dana darurat, kamu panik dan utang ke teman.',
                'scoreChange' => -5,
                'action' => 'Pindah ke Kotak Dana Darurat',
                'categories' => 'Dana Darurat',
                'tags' => 'Emergency, Debt',
                'difficulty' => 1,
                'expected_benefit' => 5,
                'learning_objective' => 'Pentingnya memiliki dana darurat untuk kejadian tak terduga.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_02',
                'type' => 'RISK',
                'title' => 'Sakit Tanpa Asuransi',
                'narration' => 'Kamu sakit tapi tidak punya asuransi, biaya berobat bikin kamu terpaksa pinjam pinjol.',
                'scoreChange' => -6,
                'action' => 'Pindah ke Kotak Asuransi Kesehatan',
                'categories' => 'Asuransi Kesehatan',
                'tags' => 'Insurance, Health, Debt',
                'difficulty' => 1,
                'expected_benefit' => 6,
                'learning_objective' => 'Memahami risiko finansial akibat sakit tanpa proteksi asuransi.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_03',
                'type' => 'RISK',
                'title' => 'Motor Bocor Ban',
                'narration' => 'Motor kamu bocor ban, terpaksa mengorbankan tabungan pendidikan untuk biaya transport.',
                'scoreChange' => -4,
                'action' => 'Pindah ke Kotak Transport',
                'categories' => 'Transport',
                'tags' => 'Transport, Saving Leakage',
                'difficulty' => 1,
                'expected_benefit' => 4,
                'learning_objective' => 'Menjaga pos pengeluaran agar tidak mengganggu tabungan tujuan khusus.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_04',
                'type' => 'RISK',
                'title' => 'Dompet Hilang',
                'narration' => 'Dompetmu hilang, karena tidak terbiasa cashless dan tidak punya backup dana.',
                'scoreChange' => -7,
                'action' => 'Pindah ke Kotak Tabungan',
                'categories' => 'Tabungan',
                'tags' => 'Security, Cashless',
                'difficulty' => 1,
                'expected_benefit' => 7,
                'learning_objective' => 'Diversifikasi penyimpanan uang dan metode pembayaran.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_05',
                'type' => 'RISK',
                'title' => 'Terlambat Bayar Cicilan Paylater',
                'narration' => 'Kamu terlambat membayar cicilan paylater, kena denda dan reputasi keuanganmu tercoreng.',
                'scoreChange' => -5,
                'action' => 'Pindah ke Kotak Paylater',
                'categories' => 'Utang',
                'tags' => 'Paylater, Credit Score, Debt',
                'difficulty' => 1,
                'expected_benefit' => 5,
                'learning_objective' => 'Disiplin membayar cicilan tepat waktu untuk menghindari denda.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_06',
                'type' => 'RISK',
                'title' => 'Investasi Kripto Abal-Abal',
                'narration' => 'Kamu investasi di kripto abal-abal tanpa riset, uangmu hilang.',
                'scoreChange' => -6,
                'action' => 'Pindah ke Kotak Cryptocurrency',
                'categories' => 'Investasi',
                'tags' => 'Crypto, Scam, Risk',
                'difficulty' => 1,
                'expected_benefit' => 6,
                'learning_objective' => 'Pentingnya riset (DYOR) sebelum berinvestasi di aset berisiko tinggi.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_07',
                'type' => 'RISK',
                'title' => 'Salah Hitung Anggaran',
                'narration' => 'Kamu salah hitung anggaran, uang habis sebelum akhir bulan dan terpaksa gali lubang tutup lubang.',
                'scoreChange' => -4,
                'action' => 'Pindah ke Kotak Anggaran (acak dadu 1-3)',
                'categories' => 'Anggaran',
                'tags' => 'Budgeting, Cashflow',
                'difficulty' => 1,
                'expected_benefit' => 4,
                'learning_objective' => 'Ketelitian dalam menyusun anggaran bulanan.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_08',
                'type' => 'RISK',
                'title' => 'Nongkrong Over Budget',
                'narration' => 'Kamu terlalu sering nongkrong, karena FOMO anggaranmu jebol dan tabungan kosong.',
                'scoreChange' => -3,
                'action' => 'Pindah ke Kotak Nongkrong',
                'categories' => 'Gaya Hidup',
                'tags' => 'Lifestyle, FOMO, Budgeting',
                'difficulty' => 1,
                'expected_benefit' => 3,
                'learning_objective' => 'Mengendalikan pengeluaran gaya hidup dan menghindari FOMO.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_09',
                'type' => 'RISK',
                'title' => 'Tidak Bayar Iuran BPJS',
                'narration' => 'Kamu tidak bayar iuran BPJS, saat sakit kamu tidak bisa klaim layanan kesehatan.',
                'scoreChange' => -7,
                'action' => 'Pindah ke Kotak Asuransi Kesehatan',
                'categories' => 'Asuransi Kesehatan',
                'tags' => 'Insurance, Compliance',
                'difficulty' => 1,
                'expected_benefit' => 7,
                'learning_objective' => 'Kewajiban membayar iuran asuransi untuk memastikan perlindungan aktif.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_RISK_10',
                'type' => 'RISK',
                'title' => 'Impulse Buying di E-commerce',
                'narration' => 'Kamu tergoda belanja online, diskon palsu bikin kamu membeli barang tak penting.',
                'scoreChange' => -5,
                'action' => 'Pindah ke Kotak Anggaran (acak dadu 1-3)',
                'categories' => 'Anggaran',
                'tags' => 'Shopping, Impulse Buying',
                'difficulty' => 1,
                'expected_benefit' => 5,
                'learning_objective' => 'Menghindari belanja impulsif dan mengenali strategi marketing diskon.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],

            // =============================================
            // KARTU KESEMPATAN (CHANCE CARDS)
            // Sumber: 
            // =============================================
            [
                'id' => 'CARD_OPP_01',
                'type' => 'CHANCE',
                'title' => 'Menabung Rutin',
                'narration' => 'Kamu berhasil konsisten menabung setiap minggu.',
                'scoreChange' => 7,
                'action' => 'Pindah ke Kotak Tabungan',
                'categories' => 'Tabungan',
                'tags' => 'Savings, Discipline',
                'difficulty' => 1,
                'expected_benefit' => 7,
                'learning_objective' => 'Membangun kebiasaan menabung yang konsisten.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_02',
                'type' => 'CHANCE',
                'title' => 'Dana Darurat Tersedia',
                'narration' => 'HP mu rusak, tapi kamu bisa pakai dana darurat tanpa panik.',
                'scoreChange' => 6,
                'action' => 'Pindah ke Kotak Dana Darurat',
                'categories' => 'Dana Darurat',
                'tags' => 'Emergency Fund, Security',
                'difficulty' => 1,
                'expected_benefit' => 6,
                'learning_objective' => 'Manfaat nyata memiliki dana darurat saat terjadi musibah.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_03',
                'type' => 'CHANCE',
                'title' => 'Investasi Cerdas',
                'narration' => 'Kamu membeli reksadana pasar uang sesuai tujuan jangka pendek.',
                'scoreChange' => 5,
                'action' => 'Pindah ke Kotak Investasi Reksadana',
                'categories' => 'Investasi',
                'tags' => 'Mutual Fund, Investment',
                'difficulty' => 1,
                'expected_benefit' => 5,
                'learning_objective' => 'Memilih instrumen investasi yang sesuai dengan tujuan keuangan.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_04',
                'type' => 'CHANCE',
                'title' => 'Bayar Cicilan Tepat Waktu',
                'narration' => 'Kamu disiplin melunasi cicilan paylater sebelum jatuh tempo.',
                'scoreChange' => 6,
                'action' => 'Pindah ke Kotak Paylater',
                'categories' => 'Utang',
                'tags' => 'Credit Score, Discipline',
                'difficulty' => 1,
                'expected_benefit' => 6,
                'learning_objective' => 'Menjaga skor kredit dengan membayar tagihan tepat waktu.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_05',
                'type' => 'CHANCE',
                'title' => 'Gunakan Promo Bijak',
                'narration' => 'Kamu menggunakan promo ojek online hanya saat perlu, sehingga anggaran jadi hemat.',
                'scoreChange' => 4,
                'action' => 'Pindah ke Kotak Anggaran (Makan/Transport)',
                'categories' => 'Anggaran',
                'tags' => 'Frugal Living, Smart Spending',
                'difficulty' => 1,
                'expected_benefit' => 4,
                'learning_objective' => 'Memanfaatkan promosi untuk efisiensi pengeluaran, bukan konsumtif.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_06',
                'type' => 'CHANCE',
                'title' => 'Punya Asuransi Kesehatan',
                'narration' => 'Kamu sakit, tapi semua biaya ditanggung oleh BPJS/asuransi kesehatan.',
                'scoreChange' => 7,
                'action' => 'Pindah ke Kotak Asuransi Kesehatan',
                'categories' => 'Asuransi Kesehatan',
                'tags' => 'Insurance, Protection',
                'difficulty' => 1,
                'expected_benefit' => 7,
                'learning_objective' => 'Perlindungan aset melalui asuransi kesehatan.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_07',
                'type' => 'CHANCE',
                'title' => 'Atur Anggaran Makan',
                'narration' => 'Kamu berhasil menjaga anggaran makan tetap seimbang tanpa boros.',
                'scoreChange' => 5,
                'action' => 'Pindah ke Kotak Anggaran Makan',
                'categories' => 'Anggaran',
                'tags' => 'Budgeting, Food',
                'difficulty' => 1,
                'expected_benefit' => 5,
                'learning_objective' => 'Disiplin dalam pengelolaan pos pengeluaran rutin.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_08',
                'type' => 'CHANCE',
                'title' => 'Menolak Pinjol',
                'narration' => 'Kamu menolak tawaran pinjol ilegal karena sadar risikonya tinggi.',
                'scoreChange' => 6,
                'action' => 'Pindah ke Kotak Utang (Pinjol)',
                'categories' => 'Utang',
                'tags' => 'Risk Awareness, Debt',
                'difficulty' => 1,
                'expected_benefit' => 6,
                'learning_objective' => 'Mengidentifikasi dan menghindari risiko pinjaman ilegal.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_09',
                'type' => 'CHANCE',
                'title' => 'Investasi Saham Blue Chip',
                'narration' => 'Kamu mulai rutin menabung saham di perusahaan stabil (blue chip).',
                'scoreChange' => 7,
                'action' => 'Pindah ke Kotak Investasi Saham',
                'categories' => 'Investasi',
                'tags' => 'Stocks, Investing',
                'difficulty' => 1,
                'expected_benefit' => 7,
                'learning_objective' => 'Strategi investasi jangka panjang pada aset berfundamental baik.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
            [
                'id' => 'CARD_OPP_10',
                'type' => 'CHANCE',
                'title' => 'Rencana Pendidikan',
                'narration' => 'Kamu menyiapkan tabungan khusus untuk biaya skripsi.',
                'scoreChange' => 5,
                'action' => 'Pindah ke Kotak Tujuan Jangka Panjang (Pendidikan)',
                'categories' => 'Tujuan Jangka Panjang',
                'tags' => 'Education, Goal Setting',
                'difficulty' => 1,
                'expected_benefit' => 5,
                'learning_objective' => 'Perencanaan keuangan untuk mencapai tujuan pendidikan.',
                'weak_area_relevance' => null,
                'cluster_relevance' => null,
                'historical_success_rate' => 0.5,
                'created_at' => $now,
            ],
        ]);
    }
}